# Generated by Django 5.0.6 on 2024-05-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leaders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=222)),
                ('name_ru', models.CharField(max_length=222, null=True)),
                ('name_uz', models.CharField(max_length=222, null=True)),
                ('image', models.ImageField(upload_to='leaders/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('position', models.CharField(max_length=222, verbose_name='Lavozimi')),
                ('position_ru', models.CharField(max_length=222, null=True, verbose_name='Lavozimi')),
                ('position_uz', models.CharField(max_length=222, null=True, verbose_name='Lavozimi')),
                ('phone', models.CharField(max_length=222)),
                ('email', models.CharField(max_length=222)),
                ('work_time', models.CharField(max_length=222, verbose_name='Ish vaqti')),
                ('work_time_ru', models.CharField(max_length=222, null=True, verbose_name='Ish vaqti')),
                ('work_time_uz', models.CharField(max_length=222, null=True, verbose_name='Ish vaqti')),
            ],
            options={
                'verbose_name': 'Rahbariyat',
                'verbose_name_plural': 'Rahbariyat',
            },
        ),
        migrations.CreateModel(
            name='LegalDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=222)),
                ('name_ru', models.CharField(max_length=222, null=True)),
                ('name_uz', models.CharField(max_length=222, null=True)),
                ('link', models.URLField(max_length=222)),
            ],
            options={
                'verbose_name': 'Huquqiy Hujjat',
                'verbose_name_plural': 'Huquqiy Hujjatlar',
            },
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=222)),
                ('name_ru', models.CharField(max_length=222, null=True)),
                ('name_uz', models.CharField(max_length=222, null=True)),
                ('logo', models.ImageField(upload_to='links/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Foydali havola',
                'verbose_name_plural': 'Foydali havolalar',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('title_ru', models.TextField(null=True)),
                ('title_uz', models.TextField(null=True)),
                ('content', models.TextField()),
                ('content_ru', models.TextField(null=True)),
                ('content_uz', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='news/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RegionUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=222)),
                ('name_ru', models.CharField(max_length=222, null=True)),
                ('name_uz', models.CharField(max_length=222, null=True)),
                ('image', models.ImageField(upload_to='region_units/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('position', models.CharField(max_length=222, verbose_name='Lavozimi')),
                ('position_ru', models.CharField(max_length=222, null=True, verbose_name='Lavozimi')),
                ('position_uz', models.CharField(max_length=222, null=True, verbose_name='Lavozimi')),
                ('phone', models.CharField(max_length=222)),
                ('email', models.CharField(max_length=222)),
                ('work_time', models.CharField(max_length=222, verbose_name='Ish vaqti')),
                ('work_time_ru', models.CharField(max_length=222, null=True, verbose_name='Ish vaqti')),
                ('work_time_uz', models.CharField(max_length=222, null=True, verbose_name='Ish vaqti')),
                ('date_birth', models.CharField(max_length=222, verbose_name="Tug'ilgan vaqti")),
                ('place_birth', models.CharField(max_length=222, verbose_name="Tug'ilgan joyi")),
                ('place_birth_ru', models.CharField(max_length=222, null=True, verbose_name="Tug'ilgan joyi")),
                ('place_birth_uz', models.CharField(max_length=222, null=True, verbose_name="Tug'ilgan joyi")),
                ('specialty', models.CharField(max_length=222, verbose_name='Mutaxasisligi')),
                ('specialty_ru', models.CharField(max_length=222, null=True, verbose_name='Mutaxasisligi')),
                ('specialty_uz', models.CharField(max_length=222, null=True, verbose_name='Mutaxasisligi')),
                ('nationality', models.CharField(max_length=222, verbose_name='Millati')),
                ('nationality_ru', models.CharField(max_length=222, null=True, verbose_name='Millati')),
                ('nationality_uz', models.CharField(max_length=222, null=True, verbose_name='Millati')),
                ('party', models.CharField(max_length=222, verbose_name='Partiyaviyligi')),
                ('party_ru', models.CharField(max_length=222, null=True, verbose_name='Partiyaviyligi')),
                ('party_uz', models.CharField(max_length=222, null=True, verbose_name='Partiyaviyligi')),
                ('malumoti', models.CharField(max_length=222, verbose_name="Ma'lumoti")),
                ('malumoti_ru', models.CharField(max_length=222, null=True, verbose_name="Ma'lumoti")),
                ('malumoti_uz', models.CharField(max_length=222, null=True, verbose_name="Ma'lumoti")),
                ('tamomlagan', models.CharField(max_length=222, verbose_name='Tamomlagan')),
                ('tamomlagan_ru', models.CharField(max_length=222, null=True, verbose_name='Tamomlagan')),
                ('tamomlagan_uz', models.CharField(max_length=222, null=True, verbose_name='Tamomlagan')),
                ('ilmiy_daraja', models.CharField(max_length=222, verbose_name='Ilmiy Darajasi')),
                ('ilmiy_daraja_ru', models.CharField(max_length=222, null=True, verbose_name='Ilmiy Darajasi')),
                ('ilmiy_daraja_uz', models.CharField(max_length=222, null=True, verbose_name='Ilmiy Darajasi')),
                ('ilmiy_unvon', models.CharField(max_length=222, verbose_name='Ilmiy unvoni')),
                ('ilmiy_unvon_ru', models.CharField(max_length=222, null=True, verbose_name='Ilmiy unvoni')),
                ('ilmiy_unvon_uz', models.CharField(max_length=222, null=True, verbose_name='Ilmiy unvoni')),
                ('language', models.CharField(max_length=222, verbose_name='Qaysi chet tillarini bilishi?')),
                ('language_ru', models.CharField(max_length=222, null=True, verbose_name='Qaysi chet tillarini bilishi?')),
                ('language_uz', models.CharField(max_length=222, null=True, verbose_name='Qaysi chet tillarini bilishi?')),
                ('davlat_mukofoti', models.CharField(max_length=222, verbose_name='Davlar mukofotlari?')),
                ('davlat_mukofoti_ru', models.CharField(max_length=222, null=True, verbose_name='Davlar mukofotlari?')),
                ('davlat_mukofoti_uz', models.CharField(max_length=222, null=True, verbose_name='Davlar mukofotlari?')),
                ('xald_deputatlari', models.CharField(max_length=222, verbose_name="Xald deputatlari, organlar a'zosimi?")),
                ('xald_deputatlari_ru', models.CharField(max_length=222, null=True, verbose_name="Xald deputatlari, organlar a'zosimi?")),
                ('xald_deputatlari_uz', models.CharField(max_length=222, null=True, verbose_name="Xald deputatlari, organlar a'zosimi?")),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('title_ru', models.TextField(null=True)),
                ('title_uz', models.TextField(null=True)),
                ('content', models.TextField()),
                ('content_ru', models.TextField(null=True)),
                ('content_uz', models.TextField(null=True)),
                ('background_image', models.ImageField(upload_to='sliders/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Slayder',
                'verbose_name_plural': 'Slayderlar',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('title_ru', models.TextField(null=True)),
                ('title_uz', models.TextField(null=True)),
                ('video_file', models.FileField(upload_to='videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videolar',
                'ordering': ['-id'],
            },
        ),
    ]
